name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: echo 'LIBQUICKJSC_TEST_PATH="$PWD/test/linux/libquickjs_c_bridge_plugin.so"' >> $GITHUB_ENV
    - run: echo $GITHUB_ENV
    - run: flutter test